#!/bin/bash

echo "🧪 Testing Role-Based UI Display"
echo "================================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Open your browser and go to: http://localhost:5173/login"
echo "2. Login with credentials:"
echo "   Email: trav@mail.com"
echo "   Password: Clover*403"
echo ""
echo "3. After successful login, you should be redirected to /dashboard"
echo ""
echo "4. Expected behavior for role 'ethack':"
echo "   ✅ Sidebar should be visible on the left"
echo "   ✅ Sidebar should show: Dashboard, Scans, Targets, AI Copilot, OWASP Top 10"
echo "   ✅ Sidebar should show: Products, Ethical Hackers, Messages, Incoming Orders"
echo "   ✅ Sidebar should show: My Products (under 'My Services')"
echo "   ✅ NO Navbar at the top (only for regular users)"
echo ""
echo "5. Open browser console (F12) and check for logs:"
echo "   - Look for: [Layout] Rendering with user: trav@mail.com role: ethack"
echo "   - Look for: [Layout] hasSidebar: true"
echo "   - Look for: [Layout] Showing SIDEBAR layout for role: ethack"
echo ""
echo "6. If you see Navbar instead of Sidebar, or role is 'user' instead of 'ethack':"
echo "   - Clear browser cache and localStorage"
echo "   - Logout and login again"
echo "   - Check console logs for role verification issues"
echo ""
echo "Press Ctrl+C to exit..."
echo ""

# Keep the script running so user can read it
tail -f /dev/null
